# Generated by Django 4.2.13 on 2024-07-14 07:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='na', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
