# Generated by Django 4.2.13 on 2024-06-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
